### ISSUE TITLE
[bug] No Update All button on iPad

### ISSUE THREAD

**Issue by jefro108** [eni9889/App-Admin-Issues#1]
The tweak works fine in my iPhone but on my iPad the settings icon for App Admin replaces the Update All button in the header. If I disable the tweak in iCleanerPro then the button is back. 

I'm on iOS 9.3.3, latest beta version.

**Comment by Haeckli** [comment]
Can confirm this from my end. "Update All" not available on the iPad (Air2) on IOS 9.3.3. This starts with version 70. I downgraded to v69 where its still OK. 
iPhone6 (IOS 9.3.3) working fine even with v71.

**Comment by 2600box** [comment]
The same here. I am on 1.0r71
